"""To use this script supply the name of your ITS1 file generated by ITSx, the fasta file generated by mothur that you used in ITSx, and the output name you would like for your accnos file. Valid output names are in the form xxxx.accnos. If your files are not in the same location as this script, include the full file path to where they are located. Example: python create_accnos.py its19.ITS1.fasta its19.mothur.fasta nontargets.accnos
"""
import sys
import numpy as np

if __name__ == "__main__":
    its1 = str(sys.argv[1])
    mothur = str(sys.argv[2])
    outfile = str(sys.argv[3])
    
    f = open(its1, "r")
    flines = f.read()
    f.close()
    frecords = flines.split(">")[1:]
    its1seqs = [x.split("\n")[0] for x in frecords]
    
    f = open(mothur, "r")
    flines = f.read()
    f.close()
    frecords = flines.split(">")[1:]
    mothurseqs = [x.split("\t")[0] for x in frecords]
    
    nontarget_accnos = np.setdiff1d(mothurseqs, its1seqs)  
    
    print("All sequences")
    print(str(len(mothurseqs)))
    print("Non-target sequences")
    print(str(len(nontarget_accnos)))
    print("ITS1 sequences")
    print(str(len(its1seqs)))
    
    g = open(outfile, "w")
    for seq in nontarget_accnos:
        g.write(seq+"\n")
    
    print("Complete.")
    g.close()
    
    